name: python 3.10
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - cmake
  - make
  - numpy
  - gdal
  - matplotlib
  - cartopy
  - geopandas
  - libgdal-arrow-parquet
  - pyearth=0.1.25
  - pyflowline=0.3.9
  - hexwatershed=0.2.30

