name: hexwatershed
channels:
  - conda-forge
dependencies:
  - python
  - jupyterlab
  - cmake
  - make
  - numpy
  - gdal
  - matplotlib
  - cartopy
  - geopandas
  - libgdal-arrow-parquet
  - pyearth=0.1.26
  - pyflowline=0.3.10
  - hexwatershed=0.2.30

